### ISSUE TITLE
Code fails while decrypting signature.

### ISSUE THREAD

**Issue by Porush** [kombiahrk/Offline-Aadhaar-EKYC-Verification#1]
Hi, I used your code in my program but it's failing while decrypting signature. I tried to add no padding parameter but generated signature didn't match with signed_info. Can you check if the code is still working with current offline e-kyc xml files.

Thanks

**Comment by big89** [comment]
@Porush Is your issue resolved?

@kombiahrk We're facing same issue, could you please help us with. Thanks!

**Comment by kombiahrk** [comment]
Will check and update if possible kindly share error screenshot

**Comment by big89** [comment]
@kombiahrk Thanks for your prompt response.

It seems issue at openssl_public_decrypt in verify.php and we tried different ways, but no luck.

When tried to get errors for openssl_public_decrypt function, it shows like -

error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
error:04067072:rsa routines:rsa_ossl_public_decrypt:padding check failed

Please check and help to resolve the issue as this is something urgent.

Thanks in advance.

**Comment by Porush** [comment]
Hi @big89, Yes my issue resolved. It's been months so I don't remember what the problem was. You can check the gist of working function for solution.

https://gist.github.com/Porush/b887c48b569cb988ebf5a03da0dfdbd5

**Comment by kombiahrk** [comment]
> routines:rsa_ossl_public_decrypt:padding

Repace the updated public key file and try

**Comment by big89** [comment]
Thanks @Porush for sharing source code. But its also not working with the provided .cer certificate version.

And thanks a lot @kombiahrk for your help, as we already resolved this issue by using same code & updated public key certificate from https://www.uidai.gov.in/images/authDoc/uidai_offline_publickey_26022021.cer
